[package]
name = "myTrainerlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.19.0"
rand = "0.8.5"
ejni = "0.0.1"
bincode = "1.1.3"
[lib]
crate-type = ["cdylib"]